name: GitHub Actions Demo

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
env:
  MY_HOST: '127.0.0.1'

jobs:
  build-job:
    runs-on: ubuntu-latest
    env:
      FULLNAME: 'Megvii'
    steps:
      - run: echo  "${{ vars.COMPANY_NAME }}"
      - run: echo  "${{ secrets.MYSQL_PASSWORD }}"
      - run: echo  "hello ${{ github.actor }}"
      - run: echo  "ref ${{ github.ref }}"
      - run: echo  "My Host $MY_HOST and $FULLNAME"

  test-job:
    runs-on: ubuntu-latest
    needs: build-job #ให้ build-job ทำเสร็จก่อน แล้วค่อยทำ test-job
    steps:
      - run: echo "test job"
      - run: echo  "repo is ${{ github.repository }}"
      - run: echo  "My Host is ${{ env.MY_HOST }}"

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job #ให้ test-job ทำเสร็จก่อน แล้วค่อยทำ deploy-job
    steps:
      - run: echo "deploy job to production server ${{ job.status }}"
